on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Release+Changelog v1

jobs:
  build:
    name: Create Release+Changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Generate changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v2
        with:
          tag-prefix: 'v'
          release-count: '1' 
          package-json: 'package.json' 
          github-token: ${{ secrets.github_token }}
          output-file: 'CHANGELOG.md'
          
      - name: Create Release
        uses: actions/create-release@v1
        env:
         GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
         tag_name: ${{ steps.changelog.outputs.tag }}
         release_name: ${{ steps.changelog.outputs.tag }}
         body: ${{ steps.changelog.outputs.clean_changelog }}
